# Required
github_username: "goswamineel976@gmail.com"
github_password: "n0123g123"
# Optional
github_totp_seed: "ABCDEF1234567890" # Obtained via https://github.com/settings/two_factor_authentication/verify
